# Generated by Django 3.2.1 on 2021-05-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=65)),
                ('secret', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('symbol', models.CharField(max_length=10)),
                ('position', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=65)),
                ('side', models.CharField(max_length=5)),
                ('quantity', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
